### ISSUE TITLE
How to create multiple ServiceBrowser instances with one server

### ISSUE THREAD

**Issue by FranziskaArndt** [holoplot/go-avahi#14]
Hi,
I would like to write a go program which can search for multiple services in parallel (with the same service name as well as with different names). For that purpose I made some tests to get familiar with this library:
```
func searchService(sb *avahi.ServiceBrowser, srv *avahi.Server, t int) (avahi.Service, error) {
	var s avahi.Service
	for {
		select {
		case s = <-sb.AddChannel:
			s, err := srv.ResolveService(s.Interface, s.Protocol, s.Name,
				s.Type, s.Domain, avahi.ProtoUnspec, 0)
			if err != nil {
				return s, err
			}
			return s, err
		case <-time.After(time.Duration(t) * time.Second):
			err := errors.New("could not find instance or service")
			return s, err
		}
	}
}

func main() {
	serviceName := "_service1._tcp"
	serviceName2 := "_service2._tcp"

	conn, err := dbus.SystemBus()
	if err != nil {
		log.Fatalf("Cannot get system bus: %v", err)
	}
	server, err := avahi.ServerNew(conn)
	if err != nil {
		log.Fatalf("Avahi new failed: %v", err)
	}

	sb, err := server.ServiceBrowserNew(avahi.InterfaceUnspec, avahi.ProtoUnspec, serviceName, "local", 0)
	if err != nil {
		log.Fatalf("ServiceBrowserNew() failed: %v", err)
	}

	s, err := searchService(sb, server, 3)
	if err != nil {
		log.Fatalf("searchService() failed: %v", err)
	}
        fmt.Println(s)

	sb2, err := server.ServiceBrowserNew(avahi.InterfaceUnspec, avahi.ProtoUnspec, serviceName2, "local", 0)
	if err != nil {
		log.Fatalf("ServiceBrowserNew() failed: %v", err)
	}

	fmt.Println("sb2 created!")

	s2, err := searchService(sb2, server, 3)
	if err != nil {
		log.Fatalf("searchService() failed: %v", err)
	}

	fmt.Println(s2)

```
I got never the output "sb2 created". The second call of `ServiceBrowserNew` stucks in `c.mutex.Lock()`, because the go routine in `ServerNew` hangs in `obj.dispatchSignal(signal)`.
Is it not intended to have multiple ServiceBrowser per server?

Thank you in advance :)

**Comment by zonque** [comment]
Each `ServiceBrowser` needs to have an active dispatcher for the channel messages it ejects. These signals are synchronized through the server because of the underlying D-Bus mechanism. I suggest to run `searchService()` asynchronously and indefinitely until the service browser goes away (and in that case, call `.Free()` on it).

We're using the library for resolving multiple services, and it works fine :)

**Comment by FranziskaArndt** [comment]
Thanks for your answer!

Yes, if I collect all messages from the channel I can also start a second browser.
So, I close this issue.
