### ISSUE TITLE
Service.Port overflows if Port > 32767

### ISSUE THREAD

**Issue by alexpevzner** [holoplot/go-avahi#3]
Hi,

Service.Port is defined as int16, but TCP port number can be larger that 32767. At this case, Service.Port becomes negative.

Please, redefine it as uint16 or int.

**Comment by bdejong** [comment]
Hi Alex,

perhaps you could provide a pull request to fix this?

Bram

**Comment by alexpevzner** [comment]
Hi @bdejong 

Sure I can. But do we really need all these formalities for such a minor fix?

And another thing. Is this project still maintained?

**Comment by bdejong** [comment]
Doing a PR probably would have taken as much time as writing this thread... ;-)

And yes! It is still being used by us, so consider it maintained.

**Comment by alexpevzner** [comment]
OK. Hope my PR will be merged soon.

**Comment by alexpevzner** [comment]
ping
