### ISSUE TITLE
Method "DomainBrowserNew" with signature "iisuu" on interface "org.freedesktop.Avahi.Server" doesn't exist

### ISSUE THREAD

**Issue by makon** [holoplot/go-avahi#6]
When executing the example from the README this error occurs:

```
2020/03/30 16:12:51 DomainBrowserNew() failed: Method "DomainBrowserNew" with signature "iisuu" on interface "org.freedesktop.Avahi.Server" doesn't exist
```

You changed the signature of `func (c *Server) DomainBrowserNew(...)` in 3a2e610dafbf78b14e1a0871749ef57ee02190ba
Not sure if this was on purpose?!

**Comment by zonque** [comment]
Hmm, the signature should be `iisiu`, that's right. I just can't see where I changed the signature in that commit? In any case, it wasn't on purpose. It's not a function that our own codebase uses, so whatever broke went unnoticed. Care to post a PR?
