### ISSUE TITLE
Restructure project according to Standard Go Project Layout

### ISSUE THREAD

**Issue by makon** [holoplot/go-avahi#7]
Would you mind if we could restructure the project to fit to the very common [Standard Go Project Layout](https://github.com/golang-standards/project-layout)?

I can create a PR, if it is fine with you

**Comment by zonque** [comment]
Yes, please do. This project was the first piece of Go I've ever written, and it certainly deserves some love :)

**Comment by zonque** [comment]
Just curious - are you still planning to do this?

**Comment by makon** [comment]
Sorry, I have totally forgotten the issue. Right now time is very short and changing the project structure would lead to a breaking change because of the sub-folders. The project works and is small enough to be maintainable as it is now. I will close the issue
